### ISSUE TITLE
Bot does not respond to my slack calls.

### ISSUE THREAD

**Issue by icodefortacos** [tdmalone/working-plusplus#29]
I installed on a local web server, but this is the only output. Not sure if it's related to npm module versions.

::ffff:x.x.x.x POST / Slackbot 1.0 (+https://api.slack.com/robots)
TypeError: Cannot read property 'trim' of undefined
    at validateToken (/root/working-plusplus-master/src/app.js:52:22)
    at handlePost (/root/working-plusplus-master/src/app.js:128:22)
    at Layer.handle [as handle_request] (/root/working-plusplus-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/working-plusplus-master/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/working-plusplus-master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/working-plusplus-master/node_modules/express/lib/router/layer.js:95:5)
    at /root/working-plusplus-master/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/working-plusplus-master/node_modules/express/lib/router/index.js:335:12)
    at next (/root/working-plusplus-master/node_modules/express/lib/router/index.js:275:10)
    at /root/working-plusplus-master/node_modules/body-parser/lib/read.js:130:5

**Comment by tdmalone** [comment]
Hi @icodefortacos,

We could probably be generating a better error there, but it seems like the `SLACK_VERIFICATION_TOKEN` environment variable might not be set, or available to the web server.

The installation process is somewhat guided when using Heroku, but unfortunately I never got around to writing [this section](https://github.com/tdmalone/working-plusplus#more-information) of the readme which was meant to list the steps for installation elsewhere 😆 

Unfortunately I'm strapped for time so can't do that right now, so you might need to do a bit of digging and stepping through the code to work out the local install steps (if you do - please feel free to contribute some documentation back!) otherwise I can recommend Heroku for now, which is usually free and pretty easy to set up as per the readme.
